drop table person cascade;
drop table passenger cascade;
drop table employee cascade;
drop table pilot cascade;
drop table airplane cascade;
drop table airport cascade;
drop table route cascade;
drop table flight cascade;
drop table ticket cascade;